# Generated by Django 4.1.7 on 2023-02-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_time', models.TimeField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('is_vegetarian', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DishMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('dishes', models.ManyToManyField(related_name='menus', through='menu.DishMenu', to='menu.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dishmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menu'),
        ),
    ]
